services:
  mongodb:
    image: mongo:latest
    container_name: dev-mongodb
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "27017:27017"
    volumes:
      - /docker/db/mongodb:/data/db
