services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: dev-clickhouse
    restart: "no"
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /docker/analytics/clickhouse:/var/lib/clickhouse
